# Generated by Django 4.1.3 on 2022-12-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_rename_email_employee_eemail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
