# Generated by Django 4.1.3 on 2022-12-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='emp',
        ),
    ]
